//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MassgeInfo
    {
        public int Id { get; set; }
        public string MassgeName { get; set; }
        public string MassgeNote { get; set; }
        public string MassgeType { get; set; }
        public Nullable<bool> MassgeState { get; set; }
        public string MassgeToUserId { get; set; }
        public string MassgeSendUserId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<System.DateTime> MassgeCreateTime { get; set; }
        public Nullable<bool> MassgeExamineState { get; set; }
    }
}
