//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NETDISKDBEntities : DbContext
    {
        public NETDISKDBEntities()
            : base("name=NETDISKDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MenuInfo> MenuInfo { get; set; }
        public virtual DbSet<YUN_FileInfo> YUN_FileInfo { get; set; }
        public virtual DbSet<RoleInfo> RoleInfo { get; set; }
        public virtual DbSet<UserRoleInfo> UserRoleInfo { get; set; }
        public virtual DbSet<ShareInfo> ShareInfo { get; set; }
        public virtual DbSet<UserGroupInfo> UserGroupInfo { get; set; }
        public virtual DbSet<GroupInfo> GroupInfo { get; set; }
        public virtual DbSet<MassgeInfo> MassgeInfo { get; set; }
        public virtual DbSet<ShareLinkInfo> ShareLinkInfo { get; set; }
        public virtual DbSet<UploadFileInfo> UploadFileInfo { get; set; }
    
        public virtual int SpFileCreateAxis(string createId)
        {
            var createIdParameter = createId != null ?
                new ObjectParameter("CreateId", createId) :
                new ObjectParameter("CreateId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpFileCreateAxis", createIdParameter);
        }
    }
}
