//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YUN_FileInfo
    {
        public int FileId { get; set; }
        public string FileName { get; set; }
        public Nullable<decimal> FileSizeKb { get; set; }
        public Nullable<System.DateTime> FileCreateTime { get; set; }
        public string FileExtName { get; set; }
        public Nullable<bool> IsFolder { get; set; }
        public Nullable<bool> IsShare { get; set; }
        public string ShareTypeId { get; set; }
        public string ShareTypeName { get; set; }

        public string FileUrl { get; set; }
        public string CreateId { get; set; }
        public string ParentFileId { get; set; }
        public Nullable<bool> FileState { get; set; }
        public Nullable<System.DateTime> FileDeleteTime { get; set; }
        public string CreateName { get; set; }
        public string CreateUnitCode { get; set; }
        public string ShareFileID { get; set; }
        public Nullable<System.DateTime> ShareTime { get; set; }
        public string ShareGroupId { get; set; }
    }
}
